config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attendances
  resources :events do
    resources :charges
  end
  resources :users
  resources :teams, only: [:index]
  resources :contacts, only: [:index]

  root 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'admin_id', class_name: "Event"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  has_many :attendances
  has_many :events, through: :attendances
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
  before_action :is_owner, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @admin_events = Event.where(admin_id: @user.id)
    (@admin_events.size > 0)? (@admin = true) : (@admin = false)
    @guest_events = Event.joins(:attendances).where('attendances.user_id = ?', @user.id)
    (@guest_events.size > 0)? (@guest = true) : (@guest = false)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:mail])
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'users', :action => 'index'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:mail])
        flash[:success] = "You successfuly updated your account"
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end

    def authenticate_user
      unless current_user 
        flash[:danger] = "This section requires to be logged-in. Please log in."
        redirect_to new_user_session_url
      end
    end

    def is_owner
      if current_user.id.to_i != params[:id].to_i
        flash[:danger] = "You can't acces this page"
        redirect_to "/"
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <h3> Complete the fields !</h3>
  <div class="row justify-content-center mt-4 mb-2 ">
    <p style = "width: 200px"> First name : <input type="text" name="first_name" value="<%= @user.first_name %>"></p>
  </div>
  <div class="row justify-content-center">
    <p style = "width: 200px"> Last name : <input type="text" name="last_name" value="<%= @user.last_name %>"></p>
  </div>
  <div class="row justify-content-center">
    <p style = "width: 200px"> Description   : <input type="text" name="description" value="<%= @user.description %>"></p>
  </div>
  <div class="row justify-content-center">
    <p style = "width: 200px"> E-mail : <input type="mail" name="mail" value="<%= @user.email %>"></p>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Edit User" %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<% content_for :title, "Register" %>

<h1>Create your Account !</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<% content_for :title, @user.first_name+"' Page" %>

<!-- Junbotron User -->

<div class="jumbotron">
  <h1 class="display-4">User's Profile : <%= @user.first_name %></h1>

</div>


<!-- Profile info -->

<div class ='align-middle'>
  <div class="card mt-5 ml-5 mr-5 p-4">
    <div class="card-body">
      <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
      <p class="card-title"><strong>Bio : </strong><%= @user.description %></p>
      <p class="card-title"><strong>Mail : </strong> <%= @user.email %></p>
      <p class="card-title"><strong>Profile created on : </strong><%= @user.created_at.strftime("%d/%m/%Y") %></p>
      <p class="card-title"> <strong>Last update on : </strong><%= @user.updated_at.strftime("%d/%m/%Y") %></p></br></br>
      <% if current_user.id == @user.id %>
        <%= link_to 'Edit Basic Info', edit_user_path(@user) %>  |
        <%= link_to "Edit your password", edit_user_registration_path(@user) %> |   
        <%= link_to 'Destroy', users_path(@event), method: :delete, data: { confirm: 'Are you sure?' }  %>
      <% end %>
    </div>
  </div>
</div>

<!-- Events AS admin -->
<% if @admin %>
  <h4 class="text-center m-3"><%= @user.first_name %> is admin of <%= @admin_events.size %> events</h4>
  <% @admin_events.each do |event| %>
        <%= link_to event do %>
          <div class= "col-sm m-2 text-center" >
            <div class="card" style="width: 18rem; text-decoration: none;">
                <div class="card-body card-event">
                  <p class="text-info"><%= event.location %></p>
                  <h5 class="text-info"><%= event.title %></h5>
                  <p class="text-info"><%= event.start_date.strftime("%B %d, %Y")%></p>
                  <div class="mt-2 ">
                    <% if user_signed_in?%>
                      <% if is_event_admin?(get_admin(event))%>
                        You are administrator to this event | <%= link_to "Event Admin Page",attendances_path(event_id: event.id) %>
                      <% elsif is_current_user_guest?(event)%>
                        You are already registered for this event !
                      <% else %>
                        <%= link_to "Buy Now", new_event_charge_path(event) , class: "btn btn-danger text-white" %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
          </div>
      <% end %>
    <% end %>
<% end %>

<!-- Events AS guest -->
<% if @guest %>
  <h4 class="text-center m-3 "><%= @user.first_name %> is guest of <%= @guest_events.size %> events</h4>
  <div class="container">
    <div class="row">
      <% @guest_events.each do |event| %>
        <%= link_to event do %>
          <div class= "col-sm text-center" >
            <div class="card" style="width: 18rem; text-decoration: none;">
                <div class="card-body card-event">
                  <p class="text-info"><%= event.location %></p>
                  <h5 class="text-info"><%= event.title %></h5>
                  <p class="text-info"><%= event.start_date.strftime("%B %d, %Y")%></p>
                </div>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>