config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attendances
  resources :events do
    resources :charges
  end
  resources :users
  resources :teams, only: [:index]
  resources :contacts, only: [:index]

  root 'events#index'
end

app/models/event.rb
  class Event < ApplicationRecord
  validates :start_date, presence: true
  validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :divisible_by_five
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000}
  validates :price, presence: true
  validates_inclusion_of :price, :in => 0..1000
  validates :location, presence: true
  has_many :attendances
  has_many :users, through: :attendances

  def divisible_by_five
    if !(self.duration).nil?
      if (self.duration % 5) != 0
        self.errors[:base] << "Number must be divisible by 5!"
      end
    else
      self.errors[:base] << "Number must be positive"
    end
  end

  def is_free?
    self.price == 0
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    #figure out how to find a featured event and what it is
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @admin = User.find(@event.admin_id)
    @nb_guests = Attendance.where(event_id: @event.id).count
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(title: params[:title], 
      description: params[:description],
      location: params[:location],
      price: params[:price],
      start_date: params[:start_date],
      duration: params[:duration],
      admin_id: current_user.id)

    if @event.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created an event"
        redirect_to :controller => 'events', :action => 'show', id: @event.id
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {})
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def get_end_date(event)
    @event.start_date + @event.duration*60
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="row justify-content-center mt-4 mb-2 ">
    <p style = "width: 400px"> Title : <input style="width:400px; height:30px" type="text" name="title" value="<%= @event.title %>"></p>
  </div>
  <div class="row justify-content-center m-2">
    <p style = "width: 400px"> Description   : <input style="width:400px; height:30px" type="text" name="description" value="<%= @event.description %>"></p>
  </div>
  <div class="row justify-content-center m-2">
    <p style = "width: 400px"> Location : <input style="width:400px; height:30px" type="text" name="location" value="<%= @event.location %>"></p>
  </div>
  <div class="row justify-content-center m-2">
    <p style = "width: 400px"> Price : <input style="width:400px; height:30px" type="number" name="price" value="<%= @event.price %>"></p>
  </div>
  <div class="row justify-content-center m-2">
    <p style = "width: 400px"> Start Date : <input style="width:400px; height:30px" type="datetime-local" name="start_date"></p>
  </div>
  <div class="row justify-content-center m-2">
    <p style = "width: 400px">Duration : <input style="width:400px; height:30px" type="number" step= 5 min=0 name="duration" value="<%= @event.duration %>"></p>
  </div>
  <div class="actions text-center mt-5">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :title, "Edit Event" %>

<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', @event %>

app/views/events/index.html.erb
<% content_for :title, "Buy Tickets for Events and Shows" %>

<!-- Caroussel of Top 3 selling events -->
<div class="carouselContainer mt-3 mb-3">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>
	  <!-- Wrapper for slides -->
	  	<div class="carousel-inner" role="listbox">
	    	<div class="carousel-item active">
	    		<%= image_tag ( "axel.jpg"),style: 'height:550px;width:1100px;' %>
	    	</div>

	    <div class="carousel-item">
	      <%= image_tag ( "angele.jpg"), style: 'height:550px;width:1100px;'%>
	    </div>

	    <div class="carousel-item">
	      <%= image_tag ( "celine.jpg"), style: 'height:550px;width:1100px;'%>
	    </div>
	  </div>
	  <!-- Controls -->
	 	<a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
	  	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
	        <span class="sr-only">Previous</span>
	    </a>
	    <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
	        <span class="carousel-control-next-icon" aria-hidden="true"></span>
	        <span class="sr-only">Next</span>
	    </a>
	</div>
</div>

<!-- List of Events -->
<div class="container-fluid">
  	<div class="row">
	    <% @events.each do |event| %>
	    	<%= link_to event do %>
			    <div class= "col-sm m-2 text-center" >
			     	<div class="card" style="width: 18rem; text-decoration: none;">
			        	<div class="card-body card-event">
			        		<p class="text-info"><%= event.location %></p>
			         		<h5 class="text-info"><%= event.title %></h5>
			         		<p class="text-info"><%= event.start_date.strftime("%B %d, %Y")%></p>
			         		<div class="mt-2	">
			         		  <span class="text-primary">
			         		  <% if user_signed_in? %>
			         		    <% if is_event_admin?(get_admin(event))%>
			         		      You are administrator to this event | <%= link_to "Event Admin Page",attendances_path(event_id: event.id) %>
			         		    <% elsif is_current_user_guest?(event)%>
			         		      You are already registered for this event !
			         		    <% elsif event.is_free? %>
			         		    	<%= link_to "Join for free", new_attendance_path(event: event,token: "0" ) , class: "btn btn-danger text-white" %>
			         		    <% else event.is_free? %>
			         		      <%= link_to "Buy Now", new_event_charge_path(event) , class: "btn btn-danger text-white" %>
			         		    <% end %>
			         		  <% end %>
			         		</span>
			         		</div>
			       		</div>
			      	</div>
			    </div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/events/new.html.erb
<% content_for :title, "Create a new Event" %>

<div class="text-center mt-5">
	<h1>New Event</h1>
	<p>Create a new Event !</p>
</div>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<% content_for :title, "Event page "+@event.title %>

<!-- Junbotron User -->
<div class="jumbotron">
  <h1 class="display-4"><%= @event.title %></h1>
</br></br>
  <p class="display-4"><%= @event.start_date.strftime("%h %d, %Y") %></p>
</div>


<!-- Event info -->
<div class ='align-middle'>
  <div class="card mt-5 ml-5 mr-5 p-4">
    <div class="card-body">
    	<h5 class="card-title"><%= @event.title %> </h5>
    	<p class="card-title"><strong>Producer : </strong><%= @admin.first_name %><%=" "%> <%=@admin.last_name %></p>
    	<p class="card-title"><strong>Start date : </strong> <%= @event.start_date.strftime("%h %d %Y, %H:%M") %></p>
      <p class="card-title"><strong>End date   : </strong> <%= get_end_date(@event).strftime("%h %d %Y, %H:%M") %> </p>
      <p class="card-title"><strong>Duration : </strong><%= @event.duration %> min</p>
    	<p class="card-title"><strong>Location : </strong><%= @event.location %></p>
    	<p class="card-title"> <strong>Description : </strong></br></br> <%= @event.description %></p></br>  </br> 
    	<p class="card-title"><strong>Event created the : </strong><%= @event.created_at.strftime("%d/%m/%Y") %></p>
    	</br>	
   		<p class="card-title"><span class="float-left"><strong>Price :</strong> <%= @event.price %>$</span>
        <span class="float-right">
        <% if user_signed_in?%>
          <% if is_event_admin?(@admin)%>
            You are administrator to this event | <%= link_to "Event Admin Page",attendances_path(event_id: @event.id) %>
          <% elsif is_current_user_guest?(@event)%>
            You are already registered for this event !
          <% else %>
            <%= link_to "Buy Now", new_event_charge_path(@event) , class: "btn btn-danger text-white float-right" %>
          <% end %>
        <% end %>
      </span>
      </p>
      </br>
   		<p  class="card-title float-left">This show has <%= @nb_guests %> participants</p></br></br>
   		<% if user_signed_in?%>
    	<% if is_event_admin?(@admin) %>
        	<%= link_to 'Edit', edit_event_path(@event) %> |
        	<%= link_to 'Destroy', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }  %>
      	<% end %>
      	<% end %>

    </div>
  </div>
</div>