config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :attendances
  resources :events do
    resources :charges
  end
  resources :users
  resources :teams, only: [:index]
  resources :contacts, only: [:index]

  root 'events#index'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :user, presence: true
  validates :event, presence: true
  after_create :new_guest_send

  def new_guest_send
    UserMailer.new_guest_send(self).deliver_now
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]
  # GET /attendances
  # GET /attendances.json
  def index
    @guests = User.joins(:attendances).where('attendances.event_id = ?', params[:event_id])
    puts @guests
    @event = Event.find(params[:event_id])
    @admin = User.find(@event.admin_id)
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    create
  end

  # GET /attendances/1/edit
  def edit
  end
  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(user: current_user, stripe_customer_id: params[:token], event: Event.find(params[:event]))

    if @attendance.save
      flash[:success] = "You successfuly attended an event"
      redirect_to :controller => 'users', :action => 'show', id: current_user.id
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error attemprint to attend an event"
      render :action => 'new'
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.fetch(:attendance, {})
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_tag url_for(action: 'create'), method: "post" do%>
   <br> </br>
     <input class="col-md-6 form-control" type="text" name="title" placeholder="Entrer le titre de votre event"/>
        <br> </br>
     <input class="col-md-6 form-control" type="datetime-local" name="start_date" placeholder="Selectionner une date et l'heure de depart de votre event"/>
     <br> </br>
     <input class="col-md-6 form-control" type="number" step= 5 name="duration" placeholder="Selectionner la durée en minutes de votre event "/>
     <br> </br>
     <input class="col-md-6 form-control" type="text" name="description" placeholder="Entrer la description de votre event"/>
     <br> </br>
     <input class="col-md-6 form-control" type="number" name="price" min="1" max="1000" placeholder="Entrer le prix de votre event"/>
     <br> </br>   
     <input class="col-md-6 form-control" type="text" name="location" placeholder="Entrer le lieu de votre event"/>
     <br> </br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<% content_for :title, "Edit attendance" %>

<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<% content_for :title, "Event page "+@event.title %>

<!-- Junbotron User -->
<div class="jumbotron">
  <h1 class="display-4"><%= @event.title %></h1>
</br></br>
  <p class="display-4"><%= @event.start_date.strftime("%h %d, %Y") %></p>
</div>


<!-- Event info -->
<div class ='align-middle'>
  <div class="card mt-5 ml-5 mr-5 p-4">
    <div class="card-body">
    	<h5 class="card-title"><%= @event.title %> </h5>
    	<p class="card-title"><strong>Producer : </strong><%= @admin.first_name %><%=" "%> <%=@admin.last_name %></p>
    	<p class="card-title"><strong>Start date : </strong> <%= @event.start_date.strftime("%h %d %Y, %H:%M") %></p>
      <p class="card-title"><strong>End date   : </strong> <%= get_end_date(@event).strftime("%h %d %Y, %H:%M") %> </p>
      <p class="card-title"><strong>Duration : </strong><%= @event.duration %> min</p>
    	<p class="card-title"><strong>Location : </strong><%= @event.location %></p>
    	<p class="card-title"> <strong>Description : </strong></br></br> <%= @event.description %></p></br>  </br> 
    	<p class="card-title"><strong>Event created the : </strong><%= @event.created_at.strftime("%d/%m/%Y") %></p>
    	</br>	
   		<p class="card-title"><span class="float-left"><strong>Price :</strong> <%= @event.price %>$</span></p>
      </br>
   		<p  class="card-title float-left">This show has <%= @nb_guests %> participants</p></br></br>
   		<% if user_signed_in?%>
    	<% if is_event_admin?(@admin) %>
        	<%= link_to 'Edit', edit_event_path(@event) %> |
        	<%= link_to 'Destroy', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }  %>
      	<% end %>
      	<% end %>

    </div>
  </div>
</div>


<!-- DISPLAY DES GUESTS-->
<h4 class="text-center m-3">You have  <%= @guests.size %> guests for this event.</h4>
<% @guests.each do |guest| %>
<p><%= guest.first_name %> <%= guest.last_name %> joined :<%= attended_on?(guest,@event) %></p>
<% end %>

app/views/attendances/new.html.erb
<% content_for :title, "Attend an event" %>

<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>